# Generated by Django 5.1.1 on 2025-01-04 00:11

import course.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, max_length=150, null=True, upload_to=course.utils.get_upload_path_course_thumbnail)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_id', models.SmallIntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('lesson_num', models.SmallIntegerField(blank=True, null=True)),
                ('follow', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('score', models.FloatField(blank=True, default=0, null=True)),
                ('videos_length', models.SmallIntegerField(blank=True, null=True)),
                ('down_num', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ManyToManyField(blank=True, related_name='courses', to='course.coursetype')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, max_length=150, null=True, upload_to=course.utils.get_upload_path_course_videos)),
                ('thumbnail', models.ImageField(blank=True, max_length=150, null=True, upload_to=course.utils.get_upload_path_course_thumbnails)),
                ('video_length', models.SmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.course')),
            ],
        ),
    ]
