# Generated by Django 5.1.1 on 2024-10-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTypes',
            new_name='CourseType',
        ),
    ]
