# Generated by Django 5.1.1 on 2024-10-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_coursetypes_coursetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetype',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='coursetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
