# Generated by Django 5.1.1 on 2024-10-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_user_course_teacher_alter_course_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_length',
        ),
        migrations.AddField(
            model_name='video',
            name='video_length',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
