# Generated by Django 5.1.1 on 2024-11-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='down_num',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='videos_length',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
