# Generated by Django 5.1.1 on 2024-12-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_lesson_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='courses', to='course.coursetype'),
        ),
    ]
