# Generated by Django 5.1.1 on 2024-12-12 22:51

import course.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to=course.utils.get_upload_path_course_videos),
        ),
    ]
