# Generated by Django 5.1.1 on 2024-10-30 13:00

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to=authentication.utils.get_upload_path_user),
        ),
    ]
